apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: frontend-service      # Name of the kubernetes resource
spec:
  type: NodePort                # Exposes the service by opening a port on each node
  selector:
    app: frontend     # Any Pod matching the label `app=polling-app-client` will be picked up by this service
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30880